version: "3"
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=tutorial
      - POSTGRES_PASSWORD=tutorial
      - POSTGRES_DB=tutorial
    ports:
      - "127.0.0.1:5432:5432"
  web:
    build: .
    restart: always
    command: python manage.py runserver 0:8000
    env_file:
      - .env
    ports: 
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db

